package com.entexy.gardenguru.ui

import com.entexy.gardenguru.data.plant.CareComplexity
import com.entexy.gardenguru.data.plant.PlantData
import com.entexy.gardenguru.data.plant.SunRelation
import com.entexy.gardenguru.data.plant.benefit.BenefitData
import com.entexy.gardenguru.data.plant.cloud.PlantCloud
import com.entexy.gardenguru.data.plant.pest.PestData
import com.entexy.gardenguru.data.plant.reproduction.Reproduction
import com.google.firebase.Timestamp
import java.util.*

object PlantMockData {
    val plant =
        PlantData(
            "id",
            "Петр",
            "Кактус",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            CareComplexity.Medium,
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight,
            arrayListOf(PestData("qweqweqwe", "Жук Олень")),
            arrayListOf(Reproduction.SEEDS),
            arrayListOf(BenefitData("qweqweqweqweqwe", "Плюсы определенно есть")),
            Date(),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        )

    val plantsData = listOf(
        PlantData(
            "id",
            "Петр",
            "Кактус",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            CareComplexity.Medium,
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight,
            arrayListOf(PestData("qweqweqwe", "Жук Олень")),
            arrayListOf(Reproduction.SEEDS),
            arrayListOf(BenefitData("qweqweqweqweqwe", "Плюсы определенно есть")),
            Date(),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
        PlantData(
            "id",
            "Петр",
            "Кактус",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            CareComplexity.Medium,
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight,
            arrayListOf(PestData("qweqweqwe", "Жук Олень")),
            arrayListOf(Reproduction.SEEDS),
            arrayListOf(BenefitData("qweqweqweqweqwe", "Плюсы определенно есть")),
            Date(),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
        PlantData(
            "id",
            "Петр",
            "Кактус",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            CareComplexity.Medium,
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight,
            arrayListOf(PestData("qweqweqwe", "Жук Олень")),
            arrayListOf(Reproduction.SEEDS),
            arrayListOf(BenefitData("qweqweqweqweqwe", "Плюсы определенно есть")),
            Date(),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
        PlantData(
            "id",
            "Петр",
            "Кактус",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            CareComplexity.Medium,
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight,
            arrayListOf(PestData("qweqweqwe", "Жук Олень")),
            arrayListOf(Reproduction.SEEDS),
            arrayListOf(BenefitData("qweqweqweqweqwe", "Плюсы определенно есть")),
            Date(),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        )
    )

    val plantsCloud = listOf(
        PlantData(
            "id",
            "Петр",
            "Кактус",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            CareComplexity.Medium,
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight,
            arrayListOf(PestData("qweqweqwe", "Жук Олень")),
            arrayListOf(Reproduction.SEEDS),
            arrayListOf(BenefitData("qweqweqweqweqwe", "Плюсы определенно есть")),
            Date(),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
    )
}