package com.entexy.gardenguru.ui

import com.entexy.gardenguru.data.plant.SunRelation
import com.entexy.gardenguru.data.plant.reproduction.Reproduction
import com.entexy.gardenguru.data.plant.search.PlantSearchCloud

object PlantSearchMOCKData {

    val plantsCloud = listOf(
        PlantSearchCloud(
            "ПетрJJJKLLLKKL",
            "Петр",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "Кактус",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight.cloudName,
            arrayListOf("qweqweqwe", "Жук Олень"),
            arrayListOf(Reproduction.SEEDS.cloudValue),
            arrayListOf("qweqweqweqweqwe", "Плюсы определенно есть"),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
        PlantSearchCloud(
            "ПетрJJJKLLLKKL",
            "Петр",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "Кактус",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight.cloudName,
            arrayListOf("qweqweqwe", "Жук Олень"),
            arrayListOf(Reproduction.SEEDS.cloudValue),
            arrayListOf("qweqweqweqweqwe", "Плюсы определенно есть"),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
        PlantSearchCloud(
            "ПетрJJJKLLLKKL",
            "Петр",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "Кактус",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight.cloudName,
            arrayListOf("qweqweqwe", "Жук Олень"),
            arrayListOf(Reproduction.SEEDS.cloudValue),
            arrayListOf("qweqweqweqweqwe", "Плюсы определенно есть"),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        ),
        PlantSearchCloud(
            "ПетрJJJKLLLKKL",
            "Петр",
            mapOf("ru" to "23423423", "en" to " wfrwerwerwe"),
            "Кактус",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKWy",
            "https://cactus.by/sites/default/files/styles/product/public/products/chi-chi-pi_edit.jpg?itok=USPbAKW",
            "https://meksika.info/wp-content/uploads/2018/09/Kaktusy-Meksiki.jpg",
            "Ка́ктусовые (лат. Cactaceae) — семейство многолетних цветковых растений порядка Гвоздичноцветные, включает около 127 родов и около 1750 видов[2], обитающих преимущественно в засушливых областях, включая одну из самых сухих пустынь мира — пустыню Атакама.",
            mapOf("ru" to "kvfmkflvdeklfvmkfmkf", "en" to " sd,. sd c.s d sdc sdc sdcsd"),
            "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО",
            mapOf("ru" to "СЕГОДНЯ ИЛИ ЗАВТРА НАДО ОБЯЗАТЕЛЬНО", "en" to "ZAVTRA"),
            "Темной весенней ночью в полночь",
            mapOf("ru" to "Темной весенней ночью в полночь", "en" to "ZAVTRA"),
            SunRelation.DirectLight.cloudName,
            arrayListOf("qweqweqwe", "Жук Олень"),
            arrayListOf(Reproduction.SEEDS.cloudValue),
            arrayListOf("qweqweqweqweqwe", "Плюсы определенно есть"),
            3,
            4,
            5,
            6,
            3,
            4,
            5,
            6
        )
    )
}